### ISSUE TITLE
Bug: time elapsed is not a function

### ISSUE THREAD

**Issue by henricattoire** [scratch-ed/blink#6]
Problem:

Run `vuurwerk` in debug mode and go back in time to a point where a firework is gliding in the air.  Then remove the future and try to continue running the program. Scratch will give the following error:

```
Uncaught TypeError TypeError: util.stackFrame.timer.timeElapsed is not a function
    at glide (/Users/.../C002309-thesis/ugent-Scratch/blink/scratch-vm/src/blocks/scratch3_motion.js:146:1)
    at execute (/Users/.../C002309-thesis/ugent-Scratch/blink/scratch-vm/src/engine/execute.js:518:1)
    at stepThread (/Users/.../C002309-thesis/ugent-Scratch/blink/scratch-vm/src/engine/sequencer.js:245:1)
    at stepThreads (/Users/.../C002309-thesis/ugent-Scratch/blink/scratch-vm/src/engine/sequencer.js:134:1)
    at _step (/Users/.../C002309-thesis/ugent-Scratch/blink/scratch-vm/src/engine/runtime.js:2149:1)
    at vm.runtime._step (/Users/.../C002309-thesis/ugent-Scratch/blink/itch/packages/core/src/context.ts:135:25)
    at <anonymous> (/Users/.../C002309-thesis/ugent-Scratch/blink/scratch-vm/src/engine/runtime.js:2753:1)
``` 

It seems like the logger is not properly logging the stackframe timer.

**Comment by henricattoire** [comment]
Logger was logging the stackframe correctly, timer object just need to be recreated when threads get deserialized in order for the error to go away. 

How Blink should handle blocks that use timer object and js promises is a [difficult question](https://docs.google.com/document/d/1SPRCXgF1xRKhHqea7QYV1swYCsBbuvV28_zIB_Y2Tv0/edit?usp=drive_link). For now, working this out will be postponed until the new execution model is completely finished.
